- apache2/Dockerfile
- sormas/Dockerfile
- sormas/setup-server.sh
New version changed the download URL for sormas.
> Changed sormas download URL

- apache2/Dockerfile
- docker-compose-build.yml
- docker-compose.yml
- payara/Dockerfile
- pg_dump/Dockerfile
- postgres/Dockerfile
- sormas/setup-server.sh
- sormas/start-server.sh
- server.log is redirected to stdout
- remove autodeployed files / folders during start and redeploy them
- health checks added
- autoheal added => container for restarting unhealthy services
> HCSA-329 and HCSA-352 - Several changes:

- docker-compose-build.yml
- keycloak/Dockerfile
- sormas/setup-server.sh
- sormas/start-server.sh
- Updated sormas setup to remove the execution of keycloak specific commands
- Updated keycloak setup with arguments
Closes #98
> Update setup to use the right sormas server url and configurations at runtime

- sormas/start-server.sh
To be merged into the `demis_integration` branch once this is merged into `development`.
Tested and working on test-de2
> Remove duplicate demis setting of interface.demis.jndiName property

- letsencrypt/root/app/le-renew.sh
fixed behaviour of le-renew.sh and added some debug output.
> HCSA-590 fix behaviour of le-renew.sh

- docker-compose-keycloak.yml
- docker-compose-s2s.yml
- docker-compose-sb-keycloak.yml
- docker-compose-sb.yml
- docker-compose.yml
- docker-compose_nginx.yml
- pg_dump/Dockerfile
- pg_dump/pg_dump
HCSA-1128 - pg_dump backuping refactor - accepts params and with additional checking:
script can be inovked with param - that sets backup alias instead of date, 
added check for existing backup with certain alias name
> HCSA-1128 - pg_dump backuping refactor - accepts params and with additional checking - dynamic db qualification to backup

- postgres/Dockerfile
- postgres/alter_system.py
Kind of an alternative suggestion for the detection of cgroup limits, but actually just cosmetic so happy to drop it again.
> Reformat postgres cgroup v2 fix #201

- sormas/start-server.sh
Fix failing sed statements stopping everything due to exit immediately mode
> Fix failing sed statements stopping everything due to exit immediately mode

- .env
- docker-compose-keycloak.yml
- docker-compose-s2s.yml
- docker-compose-sb-keycloak.yml
- docker-compose-sb.yml
- docker-compose.yml
- docker-compose_nginx.yml
- pg_dump/Dockerfile
- pg_dump/pg_dump
* Update files from ```.env``` entry
* Use [zstd](https://facebook.github.io/zstd/) to compress them
* ```BACKUP_FILES```
Type: Bash-List
Explanation: A list of files in SORMAS_PATH to be included in the back-up
Default: _"sormas-logs documents"_
Location: ```.env```
* ```BACKUP_PATH```
Type: String
Explanation: The path where find the files to be included in the back-up
Default: ```${SORMA_PATH}```
Location: ```docker-compose.yml```
> Adding file-backup functionality (HCSA-818)

- central/docker-compose.yml
- Removed import path because configuration is done by ansible.
- Removed import options in command
+ Introduced data path
> ADD data path in order to save state

- docker-compose-keycloak.yml
Hcsa 1269 -  refactored docker-compose-keycloak.yml (inherit from services-base.yml)
> Hcsa 1269 -  refactored docker-compose-keycloak.yml (inherit from services-base.yml)

- docker-compose-s2s.yml
HCSA-1270 Refactored docker-compose-s2s.yml (inherits from services-base.yml)
> HCSA-1270 Refactored docker-compose-s2s.yml (inherits from services-base.yml) 

- docker-compose-sb.yml
Hcsa 1271 refactored docker-compose-s2s.yml (inherits from services-base.yml)
> Hcsa 1271 refactored docker-compose-s2s.yml (inherits from services-base.yml)

- central/etcd/etcd.yml
- central/etcd/setup_and_run.sh
Modify certificate paths to match folder structure in project
> Correct certificate path

- postgres/Dockerfile
I added the pg_activity tool on request of the admins to as of story HSP 1875
> HSP 1875: ADD postgress analytic tools

- sormas/setup-server.sh
Removes following lines
```
<appender-ref ref="FILE_DEBUG" />
<appender-ref ref="FILE_INFO" />
<appender-ref ref="FILE_WARN" />
```
in section `<root level="debug">` on server setup.
> Dont write into application.* files

- keycloak/standalone-logging.cli
Enables Keycloak admin events to be file logged.
> HSP-3004 Configure Audit and Admin-Logging for Keycloak

- keycloak/standalone-logging.cli
Reverts hzi-braunschweig/SORMAS-Docker#398
> Revert "HSP-3004 Configure Audit and Admin-Logging for Keycloak"

- sormas/start-server.sh
This adds missing indentation to all if statements in the start-server.sh script.
> Added indentation

- apache2/Dockerfile
- build_polling_github.Jenkinsfile
https://netzlink-jira.atlassian.net/browse/HSP-2270
https://jenkins.sormas.netzlink.com/job/Build%20polling%20github%20(Jenkinsfile)/
> HSP-2270  Change "Build polling github" to use Jenkinsfile

- apache2/index.html
This adds some small changes to HTML file, which do not alter its visible content, but should cause SonarQube to stop flagging it as bugged.
https://netzlink-jira.atlassian.net/browse/HSP-4039
> Added changes suggested by SonarQube

- apache2/index.html
This adds some small changes to HTML file, which do not alter its visible content, but should cause SonarQube to stop flagging it as bugged.
https://netzlink-jira.atlassian.net/browse/HSP-4039
> Re-added SonarQube fixes to different branch

- Rscript/Dockerfile
- docker-compose-build.yml
- payara/Dockerfile
- sormas/Dockerfile
- payara ........... 5.2021.10 -> 5.2022.5
- Removed weld-integration patch (superfluous)
> SORMAS-Project #10499 Update Payara

- keycloak/Dockerfile
Fix for #534 
https://stackoverflow.com/questions/53681522/share-variable-in-multi-stage-dockerfile-arg-before-from-not-substituted
> Share KEYCLOAK_VERSION between stages

- postgres/Dockerfile
Increased postgres version to 14.10
> #12753 - Update postgreSQL from Version 14.9 to Version 14.10
